### ISSUE TITLE
Menu issue

### ISSUE THREAD

**Issue by unmick** [tranduyhung/grav-theme-mache#2]
First, it's a very nice template.
I am not using it in a one-page way.
As long as i have few pages, i have no issue with the display of the menu on the header.
When i have more entry, 
![image](https://user-images.githubusercontent.com/35163557/34777886-0354ec56-f61c-11e7-92fe-d887cecea8ef.png)

the menu appears on the body : 
![image](https://user-images.githubusercontent.com/35163557/34777744-99d7c640-f61b-11e7-9ff9-8491265020d7.png)

I don't know how to manage this strange display.

many thanks for your help

**Comment by unmick** [comment]
When i try with the antimatter template, it's well displayed.

I have change the size of the logo and i prefer how the menu is displayed.
![image](https://user-images.githubusercontent.com/35163557/34786207-c2c10f36-f633-11e7-80cf-90742655eb97.png)
if you have any advice about the logo size

**Comment by tranduyhung** [comment]
The logo is not set any width or height so it is shown in 100% width and height. Its container takes 30% of the navigation bar.

You should use small image which is not high too much, similar to the default "Mache" logo on http://peaceofmindwebsite.com/skeletons/mache/. Otherwise the navigation bar doesn't look good, especially when scrolling.
